{
    "name": """ Purchase Received product auto Selection """,
    "summary": """ Purchase Received product auto Selection """,
    "category": "Purchase",
    "images": [],
    "version": "15.0.0.2.4",
    "application": False,
    "author": "iBOS Limited",
    "support": "info@ibos.io",
    "website": "",
    "license": "LGPL-3",
    "depends": ["base", "product", "stock", "purchase", "ibos_erp_integration"],
    "data": [
    ],
    "demo": [],
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
